const dbConnection = require("../mongoConnection");
const data = require("../data/");
const books = data.book;
const users = data.user;
async function main() {
  const db = await dbConnection();
  await db.dropDatabase();

  //Create one user
  const user1 = await users.create("Wei-Hsuan","Wong","2063345306","wesley16838@gmail.com","WESLEY16838");

  //HarryPotter
  const harry1 = await books.create("Harry Potter And The Sorcerer's Stone", "J.K. Rowling","Scholastic Press","Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry. Harry makes close friends and a few enemies during his first year at the school, and with the help of his friends, Harry faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry's parents, but failed to kill Harry when he was just 15 months old.",["Fiction", "Fanasy","Drama","Thriller"],"3.79","0-7475-3009-9","uploads/harry1.png","Used Book","English","1998-08-31","HARRY POTTER");
  const harry2 = await books.create("Harry Potter And The Chamber of Secrets", "J.K. Rowling","Scholastic Press","Harry Potter and the Chamber of Secrets is a fantasy novel written by British author J. K. Rowling and the second novel in the Harry Potter series. The plot follows Harry's second year at Hogwarts School of Witchcraft and Wizardry, during which a series of messages on the walls of the school's corridors warn that the \"Chamber of Secrets\" has been opened and that the \"heir of Slytherin\" would kill all pupils who do not come from all-magical families. These threats are found after attacks which leave residents of the school petrified. Throughout the year, Harry and his friends Ron and Hermione investigate the attacks.",["Fiction", "Fanasy","Drama","Thriller"],"3.79","0-7475-3010-9","uploads/harry2.png","Used Book","English","1999-06-02","HARRY POTTER");
  const harry3 = await books.create("Harry Potter And The Prisoner of Azkaban", "J.K. Rowling","Scholastic Press","Harry Potter and the Prisoner of Azkaban is a fantasy novel written by British author J. K. Rowling and the third in the Harry Potter series. The book follows Harry Potter, a young wizard, in his third year at Hogwarts School of Witchcraft and Wizardry. Along with friends Ronald Weasley and Hermione Granger, Harry investigates Sirius Black, an escaped prisoner from Azkaban who they believe is one of Lord Voldemort's old allies.",["Fiction", "Fanasy","Drama","Thriller"],"3.79","0-7475-3011-9","uploads/harry3.png","Used Book","English","1999-09-08","HARRY POTTER");
  const harry4 = await books.create("Harry Potter And The Goblet of Fire", "J.K. Rowling","Scholastic Press","Harry Potter and the Goblet of Fire is a fantasy book written by British author J. K. Rowling and the fourth novel in the Harry Potter series. It follows Harry Potter, a wizard in his fourth year at Hogwarts School of Witchcraft and Wizardry and the mystery surrounding the entry of Harry's name into the Triwizard Tournament, in which he is forced to compete.",["Fiction", "Fanasy","Drama","Thriller"],"3.79","0-7475-3012-9","uploads/harry4.png","Used Book","English","2000-07-08","HARRY POTTER");
  const harry5 = await books.create("Harry Potter And The Order of the Phoenix", "J.K. Rowling","Scholastic Press","Harry Potter and the Order of the Phoenix is a fantasy novel written by British author J. K. Rowling and the fifth novel in the Harry Potter series. It follows Harry Potter's struggles through his fifth year at Hogwarts School of Witchcraft and Wizardry, including the surreptitious return of the antagonist Lord Voldemort, O.W.L. exams, and an obstructive Ministry of Magic. The novel was published on 21 June 2003 by Bloomsbury in the United Kingdom, Scholastic in the United States, and Raincoast in Canada. Five million copies were sold in the first 24 hours of publication.[1] It is the longest book of the series.",["Fiction", "Fanasy","Drama","Thriller"],"3.79","0-7475-3013-9","uploads/harry5.png","Used Book","English","2003-06-21","HARRY POTTER");
  const harry6 = await books.create("Harry Potter And The Half-Blood Prince", "J.K. Rowling","Scholastic Press","Harry Potter and the Half-Blood Prince is a fantasy novel written by British author J. K. Rowling and the sixth and penultimate novel in the Harry Potter series. Set during protagonist Harry Potter's sixth year at Hogwarts, the novel explores the past of Harry's nemesis, Lord Voldemort, and Harry's preparations for the final battle against Voldemort alongside his headmaster and mentor Albus Dumbledore.",["Fiction", "Fanasy","Drama","Thriller"],"3.79","0-7475-3014-9","uploads/harry6.png","Used Book","English","2005-07-16","HARRY POTTER");
  const harry7 = await books.create("Harry Potter And The Deathly Hallows", "J.K. Rowling","Scholastic Press","Harry Potter and the Deathly Hallows is a fantasy novel written by British author J. K. Rowling and the seventh and final novel of the Harry Potter series. The book was released on 21 July 2007, ending the series that began in 1997 with the publication of Harry Potter and the Philosopher's Stone. It was published in the United Kingdom by Bloomsbury Publishing, in the United States by Scholastic, and in Canada by Raincoast Books. The novel chronicles the events directly following Harry Potter and the Half-Blood Prince (2005) and the final confrontation between the wizards Harry Potter and Lord Voldemort.",["Fiction", "Fanasy","Drama","Thriller"],"3.79","0-7475-3015-9","uploads/harry7.png","Used Book","English","2007-07-21","HARRY POTTER");


  //NightSide
  const nightside1 = await books.create("Something from the Nightside", "Simon R. Green","Ace","Taylor is the name, John Taylor. My card says I’m a detective, but what I really am is an expert on finding lost things. It’s part of the gift I was born with as a child of the Nightside.\n\nI left there a long time ago, with my skin and sanity barely intact. Now I make my living in the sunlit streets of London. But business has been slow lately, so when Joanna Barrett showed up at my door, reeking of wealth, asking me to find her runaway teenage daughter, I didn’t say no.",["Science Fiction ", "Supernatural"],"10.79","0-440-01319-4","uploads/night1.png","Used Book","English","2003-05-27","NIGHTSIDE");
  const nightside2 = await books.create("Agents of Light and Darkness", "Simon R. Green","Ace","John Taylor works in the Nightside—the gaudy, neon noir, secret heart of London, where it’s always three in the morning, where gods and monsters make deals and seek pleasures they won’t find anywhere else. He has a gift for finding things. And sometimes what he's hired to locate can be very, very dangerous indeed.",["Science Fiction ", "Supernatural"],"10.79","0-441-01319-5","uploads/night2.png","Used Book","English","2003-10-28","NIGHTSIDE");
  const nightside3 = await books.create("Nightingale's Lament", "Simon R. Green","Ace","The name’s John Taylor. I work the garish streets of the Nightside—the hidden heart of London where it’s always three A.M., where in human creatures and otherworldly gods walk side by side in the endless darkness of the soul.\n I have a talent for finding things. People…property…no problem. But now I’m after something different. \nA local diva called the Nightingale has cut herself off from her family and friends, and I’ve been hired to find out the reason. I’m also wondering why her suicide—prone fans think she has a voice to die for. Literally. ",["Science Fiction ", "Supernatural"],"10.79","0-442-01319-6","uploads/night3.png","Used Book","English","2004-04-27","NIGHTSIDE");
  const nightside4 = await books.create("Hex and the City", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there. \nWhat I do is find things—people, objects—and in this case, the truth about the origins of the Nightside. \nThat’s what Lady Luck has hired me to investigate. But the more I dig, the more I discover, not about the Nightside but about the great question in my life: exactly who—and what—was my long-vanished mother.",["Science Fiction ", "Supernatural"],"10.79","0-443-01319-7","uploads/night4.png","Used Book","English","2005-02-22","NIGHTSIDE");
  const nightside5 = await books.create("Paths not Taken", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Science Fiction ", "Supernatural"],"10.79","0-444-01319-8","uploads/night5.png","Used Book","English","2005-08-30","NIGHTSIDE");
  const nightside6 = await books.create("Sharper than a Serpent's Tooth", "Simon R. Green","Ace", "My name is John Taylor. I’m a PI for hire in the Nightside, the dark and corrupt city within the city of London. Where the sun never shines and where pleasure and horror are always on sale—for the right price. \nNot a nice place to visit or a nice place to live. So you wouldn’t think I would care that it was about to be destroyed, by none other than my very own long-missing, not-quite-human mom.\nBut I do. I was born here, I live here, and I got friends here. They might not all be acceptable in polite company, but they’re my friends, nonetheless.",["Science Fiction ", "Supernatural"],"10.79","0-445-01319-8","uploads/night6.png","Used Book","English","2006-02-28","NIGHTSIDE");
  const nightside7 = await books.create("Hell to Pay", "Simon R. Green","Ace","The name’s John Taylor. I’m a PI, though what I really do is find things that are lost. I work the Nightside, the city within the city of London, where the sun never rises and where the human and inhuman go to get their kicks, provided they’re willing to pay the price in whatever currency the seller demands. \nIn the wake of the war that almost brought the Nightside to total ruin, there’s a power vacuum begging to be filled—and some think I should take charge. I don’t agree. Neither does the immortal known as the Griffin. Wealthy beyond reason, he has his own ideas about who should be running things. Still, when his granddaughter—and designated heir—is kidnapped, he calls on me to find her.",["Science Fiction ", "Supernatural"],"10.79","0-446-01319-8","uploads/night7.png","Used Book","English","2006-12-26","NIGHTSIDE");
  const nightside8 = await books.create("The Unnatural Inquirer", "Simon R. Green","Ace","John Taylor’s the name. I’m a PI working a small slice of mystical real estate in the hidden centre of London. It’s a place where the sun refuses to rise, where monsters and men walk side by side. And if you want something found in the Nightside, I’m your man.\nThe editor of the Unnatural Inquirer—the Nightside’s most notorious rag—has offered me one million pounds to find a man who claims to have evidence of the Afterlife stored on a DVD. The Inquirer made the guy a sweet deal. Then he and the disc vanished.",["Science Fiction ", "Supernatural"],"10.79","0-447-01319-8","uploads/night8.png","Used Book","English","2008-12-30","NIGHTSIDE");
  const nightside9 = await books.create("Just Another Judgement Day", "Simon R. Green","Ace","I’m John Taylor. I work as a PI out of the Nightside, that secret centre of London where clocks always read three A.M., where terrible things happen with predictable regularity, and where the always-dark streets are full of people partying like Judgement Day will never come. \nNow it may have arrived. God’s own enforcer, the righteous engine of destruction known as the Walking Man, has come to the Nightside. He’s a being whose sole purpose is the elimination of the wicked and the guilty—and given the nature of the Nightside, there’s a good chance that once he gets started, he’ll just keep on until there’s no-one left.",["Science Fiction ", "Supernatural"],"10.79","0-448-01319-8","uploads/night9.png","Used Book","English","2009-12-29","NIGHTSIDE");
  const nightside10 = await books.create("The Good, the Bad, and the Uncanny", "Simon R. Green","Ace","In the Nightside—that hidden area in the middle of London where time stands still at three A.M. and the sun won’t rise to refute it—nightmares go walking in borrowed flesh, and not everything that looks back at you with human eyes is really human.\nI’m John Taylor, a PI with a knack for finding things, helping those the Nightside has chewed up and is about to spit out. All things considered, my life lately had been bright, even in this shadowy place.",["Science Fiction ", "Supernatural"],"10.79","0-449-01319-8","uploads/night10.png","Used Book","English","2010-12-28","NIGHTSIDE");
  const nightside11 = await books.create("A Hard Day's Knight", "Simon R. Green","Ace","Welcome to the Nightside. For those foolish enough to seek it out, it’s literal tourist trap, populated by beings, human and otherwise, who have never seen the sun rise. A place where your dreams can come true—as long as your nightmares don’t get you first.\nMy name is John Taylor. I’m a PI with a special talent for finding lost things. I’m also the reluctant owner of a very special—and dangerous—weapon: Excalibur, the legendary sword (which isn’t what you think it is, and never was). Excalibur chose me, and to find out why, I’ll have to consult the last defenders of Camelot, a group of knights who dwell in a place that some find more frightening than the Nightside.",["Science Fiction ", "Supernatural"],"10.79","0-450-01319-8","uploads/night11.png","Used Book","English","2011-12-27","NIGHTSIDE");
  const nightside12 = await books.create("The Bride Wore Black Leather", "Simon R. Green","Ace","In the secret heart of London, under the cover of endless darkness, is the Nightside. But enter at your own risk. The party animals who live here may be as inhuman as their appetites... \nMy name is John Taylor. The Nightside is my home, and I’ve got a brand new full-time job there (in addition to my private eye work) as Walker—the Voice of the Authorities. I’m also marrying the love of my life, Suzie Shooter, the Nightside’s most fearsome bounty-hunter. But nothing comes easy here. Not life. Not death. And for certain, not happily-ever-after.",["Science Fiction ", "Supernatural"],"10.79","0-451-01319-8","uploads/night12.png","Used Book","English","2012-12-24","NIGHTSIDE");
 
  //Hunger
  const hunger1 = await books.create("The Hunger Games", "Suzanne Collins","Scholastic Press","In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. Long ago the districts waged war on the Capitol and were defeated. As part of the surrender terms, each district agreed to send one boy and one girl to appear in an annual televised event called, \"The Hunger Games,\" a fight to the death on live TV. Sixteen-year-old Katniss Everdeen, who lives alone with her mother and younger sister, regards it as a death sentence when she is forced to represent her district in the Games. The terrain, rules, and level of audience participation may change but one thing is constant: kill or be killed.",["Adventure‎", "Science fiction","Dystopian‎"],"15.79","0-442-11019-8","uploads/hunger1.png","New Release","English","2010-07-03","The Hunger Games");
  const hunger2 = await books.create("Catching fire", "Suzanne Collins","Scholastic Press","Suzanne Collins continues the amazing story of Katniss Everdeen in the phenomenal Hunger Games trilogy. Against all odds, Katniss Everdeen has won the annual Hunger Games with fellow district tribute Peeta Mellark. But it was a victory won by defiance of the Capitol and their harsh rules. Katniss and Peeta should be happy. After all, they have just won for themselves and their families a life of safety and plenty. But there are rumors of rebellion among the subjects, and Katniss and Peeta, to their horror, are the faces of that rebellion. The Capitol is angry. The Capitol wants revenge.",["Adventure‎", "Science fiction","Dystopian‎"],"10.79","0-440-31029-8","uploads/hunger2.png","New Release","English","2013-06-04","The Hunger Games");
  const hunger3 = await books.create("Mockingjay", "Suzanne Collins","Scholastic Press","The third book in Suzanne Collins's phenomenal and worldwide bestselling Hunger Games trilogy is now available in paperback. My name is Katniss Everdeen. Why am I not dead? I should be dead. \nKatniss Everdeen, girl on fire, has survived, even though her home has been destroyed. There are rebels. There are new leaders. A revolution is unfolding.",["Adventure‎", "Science fiction","Dystopian‎"],"10.79","0-441-01039-8","uploads/hunger3.png","Used Book","English","2014-02-25","The Hunger Games");

  //Ice and fire
  const ice1 = await books.create("A Game of Thrones", "George R. R. Martin","Bantam Books","Winter is coming. Such is the stern motto of House Stark, the northernmost of the fiefdoms that owe allegiance to King Robert Baratheon in far-off King’s Landing. There Eddard Stark of Winterfell rules in Robert’s name. There his family dwells in peace and comfort: his proud wife, Catelyn; his sons Robb, Brandon, and Rickon; his daughters Sansa and Arya; and his bastard son, Jon Snow. Far to the north, behind the towering Wall, lie savage Wildings and worse—unnatural things relegated to myth during the centuries-long summer, but proving all too real and all too deadly in the turning of the season.",["Epic fantasy"],"8.79","0-441-00229-8","uploads/ice1.png","Used Book","English","1996-08-01","Song of Ice and Fire");
  const ice2 = await books.create("A Clash of Kings", "George R. R. Martin","Bantam Books","George R. R. Martin, a writer of unsurpassed vision, power, and imagination, has created a landmark of fantasy fiction. In his widely acclaimed A Game of Thrones, he introduced us to an extraordinary world of wonder, intrigue, and adventure. Now, in the eagerly awaited second volume in this epic saga, he once again proves himself a master myth-maker, setting a standard against which all other fantasy novels will be measured for years to come.",["Epic fantasy"],"8.79","0-441-00230-8","uploads/ice2.png","Used Book","English","1999-02-02","Song of Ice and Fire");
  const ice3 = await books.create("A Storm of Swords", "George R. R. Martin","Bantam Books","Rarely has there been a tale as gripping, or one as likely to seize the minds and hearts of a generation, as George R. R. Martin's epic high fantasy series. In A Game of Thrones, an ancient kingdom was torn by the ambitions of ruthless men and women; in A Clash of Kings, war, sorcery, and madness swept over the kingdom like a voracious beast of prey. Now, as the brutal struggle for power nears its tumultuous climax, the battered and divided kingdom faces its most terrifying invasion—one that is being spearheaded from beyond the grave...",["Epic fantasy"],"8.79","0-441-00231-8","uploads/ice3.png","Used Book","English","2000-10-31","Song of Ice and Fire");
  const ice4 = await books.create("A Feast for Crows", "George R. R. Martin","Bantam Books","Few books have captivated the imagination and won the devotion and praise of readers and critics everywhere as has George R. R. Martin’s monumental epic cycle of high fantasy. Now, in A Feast for Crows, Martin delivers the long-awaited fourth book of his landmark series, as a kingdom torn asunder finds itself at last on the brink of peace . . . only to be launched on an even more terrifying course of destruction.",["Epic fantasy"],"8.79","0-441-00232-8","uploads/ice4.png","Used Book","English","2005-11-08","Song of Ice and Fire");
  const ice5 = await books.create("A Dance with Dragons", "George R. R. Martin","Bantam Books","In the aftermath of a colossal battle, the future of the Seven Kingdoms hangs in the balance once again--beset by newly emerging threats from every direction. In the east, Daenerys Targaryen, the last scion of House Targaryen, rules with her three dragons as queen of a city built on dust and death. But Daenerys has three times three thousand enemies, and many have set out to find her. Yet, as they gather, one young man embarks upon his own quest for the queen, with an entirely different goal in mind.",["Epic fantasy"],"8.79","0-441-00319-8","uploads/ice5.png","Used Book","English","2011-07-12","Song of Ice and Fire");
  


  console.log("Done seeding database");
  await db.close();
}

main();